---
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.3.2
  amd64: ghcr.io/hassio-addons/base:14.3.2
  armhf: ghcr.io/hassio-addons/base:14.3.2
  armv7: ghcr.io/hassio-addons/base:14.3.2
  i386: ghcr.io/hassio-addons/base:14.3.2
codenotary:
  signer: lucio.tarantino@gmail.com
  base_image: codenotary@frenck.dev
args:
  HDDTEMP_VERSION: "0.3-beta15"
